# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBet', models.IntegerField(unique=True)),
                ('size', models.IntegerField()),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Boxer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBoxer', models.IntegerField(unique=True)),
                ('title', models.TextField(max_length=255)),
                ('boxer_first_name', models.CharField(max_length=255)),
                ('boxer_last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFight', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('boxer1', models.TextField(max_length=255)),
                ('boxer2', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('bill', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
    ]
